### ISSUE TITLE
NavBar Component

### ISSUE THREAD

**Issue by merzoukfatima** [202306-NEA-DZ-FEW/movie-project-codenchill#3]
- [x] seperate the navigation bar into diffrent components for easier manipulation (add on 14/09/2023 11:47pm=

- [x] Logo - This could be a design or simply text of your page.

- [x] Genres - This is a drop down that include the genres of all movies. The Genres should be fetched from the API.

- [x] Movies - This is another dropdown that contains the following options ["Top Rate", "Popular", "Latest", "Now playing", "Upcoming"] - Clicking on one of these options takes the user to the movies page (#12 ) and gives them the corresponding data. Each one of those has a dedicated API route.

- [x] Actors - Goes to the Actors page (#16 ) and shows a list of all popular actors.

- [x] Search box where you can type the movie or actor name and display the related results.

- [x] shows up in all of the website

- [x] make the logo+title take you to the home page

- [x]  use SSR for better SEO

**Comment by HachemBouhadede** [comment]
This issue will be addressed in the `NavBar` branch.

**Comment by merzoukfatima** [comment]
done
