### ISSUE TITLE
Single Movie Page

### ISSUE THREAD

**Issue by KatiaGhezali** [202306-NEA-DZ-FEW/movie-project-codenchill#4]
Single Movie page - This pages shows the information about the current movie.
It should contain the following information:
- [x] The movie poster
- [x] The movie title
- [x] Release date
- [x] Runtime
- [x] Movie's Language
- [ ] The movie rating and how many votes has it received
- [x] Director's name
- [x] Overview of the movie
- [x]  The main 5 actors of the movies in the credit section (Use the API for this)
- [x] A related movies section which includes at least five related movies (Use the API for this)
- [x]  A trailer section that has the movie trailer from youtube
The movie production company name and logo.
Functionality:
- [x] Clicking an actor in the main actors should go to the single actor page.
- [x] Clicking on a movie in the related movies section should take you to the Single movie page

**Comment by merzoukfatima** [comment]
done
