### ISSUE TITLE
Single actor page

### ISSUE THREAD

**Issue by Hadj-Said-Bouras** [202306-NEA-DZ-FEW/movie-project-codenchill#7]
Single actors page - Shows information about the current actor.
The information includes:
- [x] Actor picture (If applicable. Some actors have no pics)
- [x] Actor name
- [x] Gender
- [x] Popularity
- [x] Birthday
- [x] Biography
- [x] [BONUS] - List of movies the actor participated in.

**Comment by Hadj-Said-Bouras** [comment]
I have to create the actor page

**Comment by merzoukfatima** [comment]
done
